version: 2.1

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 9b4ebad9faa576e4f9c7b612325ab8b4824506c2e60b43607a93c557edbe9ded
    docker:
    # Installation de l’image PHP
    - image: cimg/php:8.2.4
    - image: cimg/mysql:8.0
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip  
      - restore_cache:
          keys:
            # Clé de cache correspondant au fichier composer.json
            - v1-dependencies-{{ checksum "composer.json" }}
            # Clé de cache par défaut (en cas de non-correspondance avec la clé précédente)
            - v1-dependencies-
      # Installation des dépendances avec Composer
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter    
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Run tests"
          environment: 
            XDEBUG_MODE: coverage
          command: |
            ./cc-test-reporter before-build 
            composer test:CI
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?